# About
title: Reusing Data About Multiple People
sub_title: Exploring rights to data portability when the data describes more than one person
description: In collaboration with the Open Data Institute, IF researched how data portability could work when data is about multiple people.
publication_date: May 2018
url: CHANGEME

# Pages, and what order they're in
pages:
  - title: "Overview"
    class: "cover-page"
  - title: "What is data portability?"
  - title: "Data is often about more than one person"
  - title: "Section 1: Data is an abstract topic to many people"
    class: "section-1"
    custom_contents: "<p><span class=\"content_sublabel\">Section 1</span><br /><span class=\"content_label\">Data is an abstract topic to many people</span></p>"
  - title: "Section 2: Data uses, organisations and trust"
    class: "section-2"
    custom_contents: "<p><span class=\"content_sublabel\">Section 2</span><br /><span class=\"content_label\">Data uses, organisations and trust</span></p>"
  - title: "Section 3: Social relationships affect portability"
    class: "section-3"
    custom_contents: "<p><span class=\"content_sublabel\">Section 3</span><br /><span class=\"content_label\">Social relationships affect portability</span></p>"
  - title: "Section 4: Data portability can be messy"
    class: "section-4"
    custom_contents: "<p><span class=\"content_sublabel\">Section 4</span><br /><span class=\"content_label\">Data portability can be messy</span></p>"
  - title: "Summary: building the future"
    custom_contents: "<p><span class=\"content_sublabel\">Summary</span><br /><span class=\"content_label\">Building the future</span></p>"
  - title: "About this research"
    appendix: true
  - title: "Designing for data portability"
    appendix: true
  - title: "Prototypes"
    appendix: true

# Design
show_collaborator_logo: true
collaborator_name: Open Data Institute
collaborator_logo_url: "https://s3-eu-west-1.amazonaws.com/projectsbyif.com/longform/openapis.projectsbyif.com/open-data-institute.png"
collaborator_url: "https://theodi.org"

# Licence
show_licence: true
licence_text: "This report is licenced under Creative Commons Attribution-ShareAlike 4.0 International"
licence_url: "https://creativecommons.org/licenses/by-sa/4.0/"

# Images
favicon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/favicon.png
apple_touch_icon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/apple_touch_icon.png
facebook_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png
twitter_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png

# TOC
show_table_of_contents: true

# Social media links
twitter_card_handle: @projectsbyif
