# About
title: Data portability and data about multiple people
sub_title: Exploring and testing opportunities for new services and stronger digital rights
description: In collaboration with the Open Data Institute, IF researched how open APIs in the telecoms sector could lead to new classes of commercial products. We found resulting effects could include personal empowerment over data held about people, as well as the creation of new mechanisms to use data for the public good.
publication_date: May 2018
url: CHANGEME

# Pages, and what order they're in
pages:
  - title: "Data portability and data about multiple people"
    class: "cover-page"
  - title: "What is data portability?"
  - title: "Data can be about multipe people"
  - title: "Section 1: There are differences in the way people think about data about themselves and multiple people"
    class: "section-1"
    custom_contents: "<p><span class=\"content_sublabel\">Section 1</span><br /><span class=\"content_label\">There are differences in the way people think about data about themselves and multiple people</span></p>"
  - title: "Section 2: The purpose for porting data and the organisations involved is key"
    class: "section-2"
    custom_contents: "<p><span class=\"content_sublabel\">Section 2</span><br /><span class=\"content_label\">The purpose for porting data and the organisations involved is key</span></p>"
  - title: "Section 3: The use of data depends on social relationships"
    class: "section-3"
    custom_contents: "<p><span class=\"content_sublabel\">Section 3</span><br /><span class=\"content_label\">The use of data depends on social relationships</span></p>"
  - title: "Section 4: Data about multiple people complicates data portability"
    class: "section-4"
    custom_contents: "<p><span class=\"content_sublabel\">Section 4</span><br /><span class=\"content_label\">Data about multiple people complicates data portability</span></p>"
  - title: "Summary: building the future"
    custom_contents: "<p><span class=\"content_sublabel\">Summary</span><br /><span class=\"content_label\">Building the future</span></p>"
  - title: "About this research"
    appendix: true
  - title: "Designing for data portability"
    appendix: true

# Design
show_collaborator_logo: true
collaborator_name: Open Data Institute
collaborator_logo_url: "https://s3-eu-west-1.amazonaws.com/projectsbyif.com/longform/openapis.projectsbyif.com/open-data-institute.png"
collaborator_url: "https://theodi.org"

# Licence
show_licence: true
licence_text: "This report is licenced under Creative Commons Attribution-ShareAlike 4.0 International"
licence_url: "https://creativecommons.org/licenses/by-sa/4.0/"

# Images
favicon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/favicon.png
apple_touch_icon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/apple_touch_icon.png
facebook_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png
twitter_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png

# TOC
show_table_of_contents: true

# Social media links
twitter_card_handle: @projectsbyif
